### ISSUE TITLE
Github CI jobs for Go 1.16 and 1.17 fail when using Gomega 1.17.0

### ISSUE THREAD

**Issue by TheDiveO** [onsi/gomega#483]
This is dazzling: I've upgraded a dependency to Gomega 1.17.0 in one of my projects, https://github.com/TheDiveO/procfsroot. When using the following Github action:

```yaml
name: build and test
on:
  push:
    branches:
    - master

jobs:

  buildandtest:
    name: Build and Test on Go ${{matrix.go}}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: ['1.17', '1.16']
    steps:
    - name: Set up Go ${{matrix.go}}
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go}}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test Go packages
      run: sudo go test -v ./...
```

...all jobs fail with both Go 1.16 and 1.17. Testing on a local system with go 1.17.2 works correctly. According to the screenshot, Go 1.16 has been deployed, but the Gomega dependency still fails. Any idea as to what goes wrong? I'm sure I did something wrong, but I simply can't spot it.

![image](https://user-images.githubusercontent.com/6920158/140719028-c82ba0d4-1cf8-489c-8f11-3d5e437abe99.png)

https://github.com/TheDiveO/procfsroot/runs/4137011326?check_suite_focus=true
